### ISSUE TITLE
good afternoon !!! i keep gettin this error 

### ISSUE THREAD

**Issue by Easyfoshezy** [SubGlitch1/OSRipper#17]
This keeps popping up and cant fix it. Any suggestions ? Thank you in advance!! Cant wait to try this super cool tool out.

8380 INFO: Processing pre-find module path hook   distutils
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/kali/OSRipper/update_or.spec", line 6, in <module>
    a = Analysis(['update_or.py'],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 348, in assemble
    self.graph = initialize_modgraph(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/analysis.py", line 613, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1473, in import_hook
    target_package, target_module_partname = self._find_head_package(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1657, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale
Generated in dist

**Comment by SubGlitch1** [comment]
Good afternoon,
I have had a look and it seems to be a pyinstaller issue as mentioned here (not an issue with osripper)

https://stackoverflow.com/questions/68459087/pyinstaller-with-python-3-10-0b4-importerror-no-module-named-bootlocale

There is a fix for it so you can change the affected line in the code and add the argument described in the post.
If you aren't able to do that lmk and I'll make a release for you and others affected by this error
